import streamlit as st
import json
import os
import glob
import plotly.graph_objects as go
import plotly.express as px
from dotenv import load_dotenv

load_dotenv()

st.set_page_config(page_title="LLM-as-Judge Dashboard", layout="wide", page_icon="⚖️")

def load_latest_json(prefix: str):
    """Load the latest JSON file matching the prefix from the reports directory."""
    files = glob.glob(f"reports/{prefix}_*.json")
    if not files:
        return None
    latest_file = max(files, key=os.path.getctime)
    with open(latest_file, "r") as f:
        return json.load(f)

# Sidebar
st.sidebar.title("⚖️ LLM Judge Dashboard")
st.sidebar.markdown("Analyze outputs of the LLM-as-Judge pipeline.")
page = st.sidebar.radio("Navigation", ["Interactive Judge", "Validation Report", "A/B Comparison"])

st.sidebar.markdown("---")
st.sidebar.subheader("Actions")

# Let user choose model to bypass specific model rate limits
judge_model = st.sidebar.selectbox(
    "Judge Model", 
    ["gemini-2.5-flash", "gemini-2.0-flash", "gpt-4o-mini", "gpt-3.5-turbo", "claude-3-5-sonnet-20240620", "claude-3-haiku-20240307"],
    help="If you hit a rate limit, try switching to a different model!"
)

if st.sidebar.button("Run Validation Suite 🧪"):
    with st.spinner(f"Running Validation Suite with {judge_model}... this may take a minute."):
        import subprocess
        import sys
        env = os.environ.copy()
        env["JUDGE_MODEL"] = judge_model
        env["PYTHONIOENCODING"] = "utf-8"
        result = subprocess.run([sys.executable, "main.py", "validate"], capture_output=True, text=True, env=env, encoding="utf-8")
        if result.returncode == 0:
            st.sidebar.success("Validation Suite completed successfully!")
            st.rerun()
        else:
            st.sidebar.error("Validation Suite failed! See terminal for details.")
            st.sidebar.code(result.stderr)

if st.sidebar.button("Run A/B Comparison 📊"):
    with st.spinner(f"Running A/B Comparison with {judge_model}... this may take a minute."):
        import subprocess
        import sys
        env = os.environ.copy()
        env["JUDGE_MODEL"] = judge_model
        env["PYTHONIOENCODING"] = "utf-8"
        result = subprocess.run([sys.executable, "main.py", "ab-report"], capture_output=True, text=True, env=env, encoding="utf-8")
        if result.returncode == 0:
            st.sidebar.success("A/B Comparison completed successfully!")
            st.rerun()
        else:
            st.sidebar.error("A/B Comparison failed! See terminal for details.")
            st.sidebar.code(result.stderr)

st.sidebar.markdown("---")
st.sidebar.info("This dashboard visualizes the structured JSON reports generated by the LLM-as-Judge pipeline, showcasing its statistical rigor and bias mitigations.")

st.markdown(f"**Current Judge Model:** `{judge_model}`")
st.markdown("---")

if page == "Interactive Judge":
    st.title("🕹️ Interactive Judge")
    st.markdown("Evaluate responses in real-time using the LLM-as-Judge.")
    
    col1, col2 = st.columns(2)
    with col1:
        sys_prompt = st.text_area("System Prompt", value="You are a helpful assistant.", height=100)
        user_input = st.text_area("User Input", value="Explain quantum computing in one sentence.", height=100)
    with col2:
        model_resp = st.text_area("Model Response (to judge)", value="Quantum computing uses quantum mechanics to process information exponentially faster than classical computers for certain tasks.", height=245)
    
    if st.button("⚖️ Run Judge"):
        if not user_input or not model_resp:
            st.error("User Input and Model Response are required.")
        else:
            with st.spinner(f"Evaluating using {judge_model}..."):
                import yaml
                from src.judge import JudgeClient
                
                # Load rubric
                with open("config/rubric.yaml", "r") as f:
                    config = yaml.safe_load(f)
                
                os.environ["JUDGE_MODEL"] = judge_model
                judge = JudgeClient(
                    model=judge_model,
                    temperature=0.0,
                    max_tokens=2048,
                    max_retries=3,
                    retry_wait_seconds=2,
                    pass_threshold=3.0
                )
                
                test_case = {
                    "id": "interactive_run",
                    "input": user_input,
                    "system_prompt": sys_prompt
                }
                
                try:
                    verdict, audit = judge.judge_pointwise(test_case=test_case, response=model_resp)
                    if verdict:
                        st.success(f"**Overall Score:** {verdict.overall_score:.2f} / 5.0")
                        st.markdown(f"**Verdict:** {'✅ Pass' if verdict.passed else '❌ Fail'}")
                        st.markdown(f"**Rationale:**\n> {verdict.overall_rationale}")
                        
                        st.subheader("Criteria Breakdown")
                        for crit, score in verdict.criteria_breakdown.items():
                            st.metric(crit.capitalize(), f"{score.score} / 5")
                        
                        with st.expander("View Raw API Audit Log"):
                            st.json(audit)
                    else:
                        st.error("Judge failed to return a valid verdict.")
                        with st.expander("View Raw API Audit Log"):
                            st.json(audit)
                except Exception as e:
                    st.error(f"Error during evaluation: {str(e)}")

elif page == "Validation Report":
    st.title("🧪 Judge Validation Report")
    st.markdown("Displays Cohen's Kappa agreement with human labels and the judge's resistance to biases (Adversarial Probes).")
    
    val_data = load_latest_json("validation_report")
    if not val_data:
        st.warning("No validation report found. Please run the validation suite.")
    else:
        # Kappa section
        st.subheader("1. Human/Gold Label Agreement")
        kappa_data = val_data.get("kappa_validation", {})
        
        col1, col2, col3 = st.columns(3)
        col1.metric("Exact Agreement", f"{kappa_data.get('exact_agreement_rate', 0):.1%}")
        col2.metric("Near Agreement (±1)", f"{kappa_data.get('near_agreement_rate', 0):.1%}")
        col3.metric("Cohen's Kappa", f"{kappa_data.get('kappa_score', 0):.3f}")
        
        # Adversarial Probe section
        st.markdown("---")
        st.subheader("2. Bias Resistance (Adversarial Probes)")
        st.markdown("Validates whether the judge is fooled by **verbosity bias** (padded fluff) or **sycophancy** (confident but incorrect).")
        
        probe_data = val_data.get("adversarial_validation", {})
        if probe_data:
            probe_types = []
            pass_rates = []
            for p_type, stats in probe_data.get("by_type", {}).items():
                probe_types.append(p_type.capitalize())
                pass_rates.append(stats.get("pass_rate", 0))
                    
            fig = px.bar(
                x=probe_types, 
                y=pass_rates,
                labels={"x": "Probe Type", "y": "Pass Rate"},
                title="Judge Defense Against Biases",
                range_y=[0, 1]
            )
            fig.update_layout(yaxis_tickformat='.0%')
            st.plotly_chart(fig, use_container_width=True)
            
            st.success(f"✅ Judge passed {probe_data.get('passed_probes', 0)} / {probe_data.get('total_probes', 0)} adversarial probes.")
        else:
            st.info("No adversarial probe data available.")

elif page == "A/B Comparison":
    st.title("📊 A/B Comparison Report")
    st.markdown("Compares two configurations (e.g. Model A vs Model B) across multiple qualitative criteria.")
    
    ab_data = load_latest_json("ab_comparison")
    if not ab_data:
        st.warning("No A/B comparison report found. Please run the A/B test suite.")
    else:
        winner = ab_data.get("winner", "Tie")
        st.success(f"🏆 Overall Winner: **{winner}**")
        
        st.subheader("Summary Metrics")
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("V1 Mean Score", f"{ab_data.get('mean_v1', 0):.2f}")
        col2.metric("V2 Mean Score", f"{ab_data.get('mean_v2', 0):.2f}", delta=f"{ab_data.get('difference', 0):+.2f}")
        col3.metric("V1 Pass Rate", f"{ab_data.get('pass_rate_v1', 0):.1%}")
        col4.metric("V2 Pass Rate", f"{ab_data.get('pass_rate_v2', 0):.1%}")
        
        # Criteria Comparison Radar Chart
        st.markdown("---")
        st.subheader("Criteria Breakdown")
        
        criteria_list = ab_data.get("criterion_comparison", [])
        if criteria_list:
            categories = [c['criterion'].capitalize() for c in criteria_list]
            v1_scores = [c['mean_v1'] for c in criteria_list]
            v2_scores = [c['mean_v2'] for c in criteria_list]
            
            fig = go.Figure()
            fig.add_trace(go.Scatterpolar(
                r=v1_scores,
                theta=categories,
                fill='toself',
                name='Model A (V1)'
            ))
            fig.add_trace(go.Scatterpolar(
                r=v2_scores,
                theta=categories,
                fill='toself',
                name='Model B (V2)'
            ))
            
            fig.update_layout(
                polar=dict(radialaxis=dict(visible=True, range=[1, 5])),
                showlegend=True,
                title="Criteria Comparison (1-5 Scale)"
            )
            st.plotly_chart(fig, use_container_width=True)
        
        # Statistical Significance
        st.markdown("---")
        st.subheader("Statistical Significance")
        is_sig = ab_data.get("is_significant", False)
        pval = ab_data.get("p_value", 1.0)
        
        if is_sig:
            st.info(f"The difference is statistically significant (p = {pval:.4f} < 0.05).")
        else:
            st.info(f"The difference is NOT statistically significant (p = {pval:.4f} >= 0.05).")
